# Accessing the New York Times API

In [1]:
import requests
import pandas as pd
import datetime as dt
from sqlalchemy import create_engine
import pandas as pd
import time
#pip install PyMySQL

## Accessing the API

In [14]:
lists_df = pd.read_csv('lists.csv')
lists_df['list_name'].str.lower().tolist()

['combined print & e-book fiction',
 'hardcover fiction',
 'paperback trade fiction',
 'combined print & e-book nonfiction',
 'hardcover nonfiction',
 'paperback nonfiction',
 'advice, how-to & miscellaneous',
 'children’s middle grade hardcover',
 'children’s picture books',
 'children’s series',
 'young adult hardcover',
 'audio fiction',
 'audio nonfiction',
 'business',
 'graphic books and manga',
 'mass market',
 'middle grade paperback',
 'young adult paperback']

In [2]:
def book_data_extraction(date, list_names):
    
    """Input
        1. dates: A list of dates or a string of the most recent New York Times bestseller list
        2. list_name: A list of different best seller lists
        
    Output
        A list dataframe with the title, author, publisbher, contributor, 
        published date, list_name, age group and weeks on list of each book """
    
    #book_dicts = []
    #lists = []
    book_data = {'weeks_on_list': [], 'publisher': [], 
                 'title': [], 'author': [], 'contributor': [], 
                 'age_group': [], 'published_date': [], 'list_name': []}
    
    lists_df = pd.read_csv('lists.csv')
    lists =  lists_df['list_name'].str.lower().tolist()
    
    #if type(date) == str:
        #pass
    #elif type(date) == list:
        #pass
    #else:
        #print('The dates given are not correct')
        #return None     

    for list_name in list_names:        
        list_name = list_name.lower()
        
        if list_name not in lists:
            print('One of the lists provided is incorrect. Please provide the correct names')
        else:
            list_name_url = list_name.replace(' ' , '-')
        
            url = f'https://api.nytimes.com/svc/books/v3/lists/{date}/{list_name_url}.json?api-key=ktKhpKGNU9A988ja0j6eDwFu4njxRxC7'
            response = requests.get(url)
            json_data = response.json()

            books_list = json_data['results']['books']
            for book in books_list:
                weeks_on_list = book['weeks_on_list']
                book_data['weeks_on_list'].append(weeks_on_list)

                publisher = book['publisher']
                book_data['publisher'].append(publisher)

                title = book['title']
                book_data['title'].append(title)

                author = book['author']
                book_data['author'].append(author)

                contributor = book['contributor']
                book_data['contributor'].append(contributor)

                age_group = book['age_group']
                book_data['age_group'].append(age_group)

                date_published = json_data['results']['published_date']
                book_data['published_date'].append(date_published)

                list_name = json_data['results']['list_name']
                book_data['list_name'].append(list_name)
                time.sleep(900) 
        
        #book_dicts.append(book_data)
        #df = pd.DataFrame.from_dict(book_data)
        #dataframes.append(df)
        
        
    #dataframes = extract_data(date_chunks, 'hardcover nonfiction')
    #df = pd.concat(dataframes, axis = 'index')
    
    return book_dicts

In [3]:
list_names = ['Hardcover nonfiction', 'Hardcover fiction']
book_dicts = book_data_extraction('2021-05-09', list_names)

In [13]:
book_dicts[1]

{'weeks_on_list': [1,
  1,
  27,
  2,
  38,
  3,
  7,
  12,
  59,
  1,
  1,
  1,
  1,
  3,
  2,
  1,
  4,
  2,
  12,
  21,
  26,
  8,
  1,
  4,
  47,
  2,
  1,
  6,
  7,
  3],
 'publisher': ['Crown',
  'Knopf',
  'Crown',
  "St. Martin's",
  'Random House',
  'Crown',
  'Simon & Schuster',
  'Viking',
  'Dial',
  "St. Martin's",
  'Abrams Image',
  'Harper Perennial',
  'Twelve',
  'Holt',
  'Doubleday',
  'Grand Central',
  'Viking',
  'Putnam',
  "St. Martin's",
  'Viking',
  'Tor/Forge',
  'Knopf',
  'Gallery',
  'Little, Brown',
  'Riverhead',
  "St. Martin's",
  'Library of America',
  'Grand Central',
  'Park Row',
  'Ecco'],
 'title': ['OUT OF MANY, ONE',
  'CRYING IN H MART',
  'GREENLIGHTS',
  'ON THE HOUSE',
  'CASTE',
  'BROKEN HORSES',
  'THE CODE BREAKER',
  'THINK AGAIN',
  'UNTAMED',
  'BLOOD AND TREASURE',
  "F*CK IT, I'LL START TOMORROW",
  'GOODBYE, AGAIN',
  'MADAM SPEAKER',
  'BROKEN',
  'EMPIRE OF PAIN',
  'A GAMBLING MAN',
  'THE HILL WE CLIMB',
  'OCEAN PREY',
  'THE FOUR WINDS',
  'THE MIDNIGHT LIBRARY',
  'THE INVISIBLE LIFE OF ADDIE LARUE',
  'KLARA AND THE SUN',
  'LOVER UNVEILED',
  'THE RED BOOK',
  'THE VANISHING HALF',
  'THE GOOD SISTER',
  'THE MAN WHO LIVED UNDERGROUND',
  'WIN',
  'THE LOST APOTHECARY',
  'GOOD COMPANY'],
 'author': ['George W. Bush',
  'Michelle Zauner',
  'Matthew McConaughey',
  'John Boehner',
  'Isabel Wilkerson',
  'Brandi Carlile',
  'Walter Isaacson',
  'Adam Grant',
  'Glennon Doyle',
  'Bob Drury and Tom Clavin',
  'Action Bronson as told to Rachel Wharton',
  'Jonny Sun',
  'Susan Page',
  'Jenny Lawson',
  'Patrick Radden Keefe',
  'David Baldacci',
  'Amanda Gorman',
  'John Sandford',
  'Kristin Hannah',
  'Matt Haig',
  'V.E. Schwab',
  'Kazuo Ishiguro',
  'J.R. Ward',
  'James Patterson and David Ellis',
  'Brit Bennett',
  'Sally Hepworth',
  'Richard Wright',
  'Harlan Coben',
  'Sarah Penner',
  "Cynthia D'Aprix Sweeney"],
 'contributor': ['by George W. Bush',
  'by Michelle Zauner',
  'by Matthew McConaughey',
  'by John Boehner',
  'by Isabel Wilkerson',
  'by Brandi Carlile',
  'by Walter Isaacson',
  'by Adam Grant',
  'by Glennon Doyle',
  'by Bob Drury and Tom Clavin',
  'by Action Bronson as told to Rachel Wharton',
  'by Jonny Sun',
  'by Susan Page',
  'by Jenny Lawson',
  'by Patrick Radden Keefe',
  'by David Baldacci',
  'by Amanda Gorman',
  'by John Sandford',
  'by Kristin Hannah',
  'by Matt Haig',
  'by V.E. Schwab',
  'by Kazuo Ishiguro',
  'by J.R. Ward',
  'by James Patterson and David Ellis',
  'by Brit Bennett',
  'by Sally Hepworth',
  'by Richard Wright',
  'by Harlan Coben',
  'by Sarah Penner',
  "by Cynthia D'Aprix Sweeney"],
 'age_group': ['',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 'published_date': ['2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09',
  '2021-05-09'],
 'list_name': ['Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Nonfiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction',
  'Hardcover Fiction']}

In [12]:
df = pd.DataFrame.from_dict(book_dicts[0])
df.tail()

,weeks_on_list,publisher,title,author,contributor,age_group,published_date,list_name
25,2,St. Martin's,THE GOOD SISTER,Sally Hepworth,by Sally Hepworth,,2021-05-09,Hardcover Fiction
26,1,Library of America,THE MAN WHO LIVED UNDERGROUND,Richard Wright,by Richard Wright,,2021-05-09,Hardcover Fiction
27,6,Grand Central,WIN,Harlan Coben,by Harlan Coben,,2021-05-09,Hardcover Fiction
28,7,Park Row,THE LOST APOTHECARY,Sarah Penner,by Sarah Penner,,2021-05-09,Hardcover Fiction
29,3,Ecco,GOOD COMPANY,Cynthia D'Aprix Sweeney,by Cynthia D'Aprix Sweeney,,2021-05-09,Hardcover Fiction

0                               George W. Bush
1                              Michelle Zauner
2                          Matthew McConaughey
3                                 John Boehner
4                             Isabel Wilkerson
5                               Brandi Carlile
6                              Walter Isaacson
7                                   Adam Grant
8                                Glennon Doyle
9                     Bob Drury and Tom Clavin
10    Action Bronson as told to Rachel Wharton
11                                   Jonny Sun
12                                  Susan Page
13                                Jenny Lawson
14                        Patrick Radden Keefe
15                              David Baldacci
16                               Amanda Gorman
17                               John Sandford
18                              Kristin Hannah
19                                   Matt Haig
20                                 V.E. Schwab
21                              Kazuo Ishiguro
22                                   J.R. Ward
23             James Patterson and David Ellis
24                                Brit Bennett
25                              Sally Hepworth
26                              Richard Wright
27                                Harlan Coben
28                                Sarah Penner
29                     Cynthia D'Aprix Sweeney
Name: author, dtype: object

In [ ]:
def weekly_book_transformation(df):
    """Input: The dataframe from the weekly_book_extraction function 
    Out: A cleaned version of the data including smaller dataframes 
    that can be loaded into the MySQL tables"""
    
    dataframes = []
    
    df['publisher'] = df.publisher.str.strip()
    df['title'] = df.title.str.capitalize().str.strip()
    df['author'] = df.author.str.strip()
    df['contributor'] = df.contributor.str.replace('by', '').str.strip()

    authors = df['author'].copy()
    dataframes.append(authors)

    publishers = df['publisher'].copy()
    dataframes.append(publishers)
    
    #Creating the dataframe for the 'books table'
    books_temp = df[['title', 'author', 'publisher']].copy()
    books_temp.drop_duplicates(['title', 'author'], keep = 'first', inplace = True)
    books = pd.merge(authors, books_temp, left_on = 'author_name', right_on = 'author', how = 'inner')
    books = pd.merge(books, publishers, left_on = 'publisher', right_on = 'publisher_name', how = 'inner')
    indices = [i for i in range(1, len(books) + 1)]
    books['book_id'] = indices
    
    return dataframes

In [ ]:
def weekly_book_loading(df):
    df['publisher'] = df.publisher.str.strip()
    df['title'] = df.title.str.capitalize().str.strip()
    df['author'] = df.author.str.strip()
    df['contributor'] = df.contributor.str.replace('by', '').str.strip()
    
    return df

In [ ]:
# list_names = ['Hardcover Fiction', 'Hardcover Nonfiction']
# df = weekly_book_extraction('2021-01-02', list_names)
# df = weekly_book_transformation(df)
# weekly_book_loading(df)

In [ ]:
engine1 = create_engine('mysql+pymysql://root@localhost:tomatoSAUC3_@localhost:3306/weclouddatamovies', echo=False)
engine = create_engine('mysql+pymysql://root@localhost:tomatoSAUC3@localhost:3306/books', echo=False)

In [ ]:
authors = pd.read_csv('authors.csv')
authors.to_sql('authors', engine)